// Type imports removed - no longer needed after mock data cleanup

export const TRANSLATIONS = {
  pt: {
    login: {
      title: 'Selecione seu Perfil de Acesso',
      attendee: 'Participante',
      attendeeDesc: 'Entrar no evento ao vivo',
      producer: 'Produtor / Admin',
      producerDesc: 'Acessar sala de controle',
      enter: 'Entrar',
      welcome: 'Bem-vindo ao',
      // Email auth
      email: 'Email',
      password: 'Senha',
      name: 'Nome',
      signIn: 'Entrar',
      signUp: 'Criar Conta',
      orContinueWith: 'ou continue com',
      useEmail: 'Usar Email',
      useGoogle: 'Usar Google',
      noAccount: 'Não tem conta?',
      hasAccount: 'Já tem conta?',
      createAccount: 'Criar conta',
      loginHere: 'Entre aqui',
      emailRequired: 'Email é obrigatório',
      passwordRequired: 'Senha é obrigatória',
      passwordMinLength: 'Senha deve ter pelo menos 6 caracteres',
      signUpSuccess: 'Conta criada! Verifique seu email para confirmar.',
      username: 'Nome de usuário',
      usernameTaken: 'Este nome de usuário já está em uso',
      usernameInvalid: 'Nome de usuário pode conter apenas letras, números, underscores e hífens',
      usernameTooShort: 'Nome de usuário deve ter pelo menos 3 caracteres',
      forgotPassword: 'Esqueceu a senha?',
      resetPassword: 'Redefinir Senha',
      sendResetLink: 'Enviar Link de Redefinição',
      backToLogin: 'Voltar ao Login',
      resetEmailSent: 'Email de redefinição enviado! Verifique sua caixa de entrada.',
      newPassword: 'Nova Senha',
      confirmPassword: 'Confirmar Senha',
      passwordsDoNotMatch: 'As senhas não coincidem',
      passwordResetSuccess: 'Senha redefinida com sucesso! Faça login.',
      enterEmailForReset: 'Digite seu email para receber o link de redefinição'
    },
    nav: {
      stage: 'Palco Principal',
      rooms: 'Salas',
      parties: 'Minhas Festas',
      agenda: 'Agenda',
      networking: 'Networking',
      admin: 'Controle',
      analytics: 'Analytics',
      settings: 'Config',
      signout: 'Sair',
      producer: 'Ferramentas de Produção'
    },
    stage: {
      live: 'AO VIVO',
      viewers: 'Espectadores',
      about: 'Sobre a Sessão',
      track: 'Trilha',
      level: 'Nível',
      addToCalendar: 'Adicionar à Agenda',
      share: 'Compartilhar'
    },
    engagement: {
      chat: 'Chat',
      qa: 'Q&A',
      polls: 'Enquetes',
      survey: 'Pesquisa',
      liveChat: 'Chat ao Vivo',
      aiSummary: 'Resumo IA',
      analyzing: 'Analisando...',
      typeMessage: 'Digite sua mensagem...',
      topQuestions: 'Principais Perguntas',
      askQuestion: 'Fazer Pergunta',
      answered: 'Respondida',
      currentPoll: 'Enquete Atual',
      votes: 'votos',
      submitFeedback: 'Enviar Feedback',
      thankYou: 'Obrigado!',
      feedbackRecorded: 'Seu feedback foi registrado.',
      noSurvey: 'Nenhuma pesquisa ativa no momento.',
      connection: 'Conexão Excelente'
    },
    admin: {
      title: 'MCR - Master Control Room',
      onAir: 'NO AR',
      streamHealth: 'Sinal & Fonte',
      activeViewers: 'Audiência Real-Time',
      registered: 'Inscritos',
      aiDirector: 'Diretor IA',
      createPoll: 'Lançar Enquete',
      createSurvey: 'Lançar Pesquisa',
      drafting: 'Gerando...',
      dangerZone: 'Zona Crítica',
      restart: 'Reiniciar Sinal',
      endEvent: 'Encerrar Transmissão',
      bitrate: 'Bitrate',
      fps: 'FPS',
      dropped: 'Perda de Quadros',
      back: 'Voltar ao Login'
    },
    reports: {
      title: 'Relatórios de Usuários',
      export: 'Exportar CSV',
      searchPlaceholder: 'Buscar por nome, email ou ID...',
      columns: {
        user: 'Usuário',
        role: 'Perfil',
        session: 'Sessão',
        engagement: 'Engajamento',
        location: 'Localização',
        actions: 'Ações'
      },
      details: {
        techInfo: 'Informações Técnicas',
        activityLog: 'Histórico de Atividades',
        questions: 'Perguntas Realizadas',
        browser: 'Navegador',
        device: 'Dispositivo',
        ip: 'Endereço IP',
        connection: 'Conexão',
        login: 'Entrada',
        logout: 'Saída',
        duration: 'Duração'
      }
    },
    rooms: {
      title: 'Sessões ao Vivo & Breakouts',
      subtitle: 'Escolha uma trilha para entrar nas sessões interativas.',
      join: 'Entrar na Sessão'
    },
    projects: {
      title: 'Gerenciar Projetos',
      createNew: 'Novo Projeto',
      selectProject: 'Selecionar Projeto',
      deleteProject: 'Excluir Projeto',
      projectName: 'Nome do Projeto',
      projectDescription: 'Descrição',
      status: 'Status',
      draft: 'Rascunho',
      live: 'Ao Vivo',
      ended: 'Encerrado',
      onDemand: 'Sob Demanda',
      onDemandDesc: 'Disponível para visualização após término',
      enableOnDemand: 'Ativar On-Demand',
      disableOnDemand: 'Desativar On-Demand',
      currentProject: 'Projeto Atual',
      noProjects: 'Nenhum projeto criado',
      confirmDelete: 'Tem certeza que deseja excluir este projeto?',
      create: 'Criar',
      cancel: 'Cancelar',
      save: 'Salvar',
      viewers: 'Visualizações',
      createdAt: 'Criado em',
      rtmpStreamKey: 'Chave RTMP',
      rtmpUrl: 'URL RTMP',
      streamingDetails: 'Detalhes de Transmissão',
      copyKey: 'Copiar Chave',
      keyCopied: 'Chave copiada!'
    }
  },
  en: {
    login: {
      title: 'Select Access Profile',
      attendee: 'Attendee',
      attendeeDesc: 'Enter live event experience',
      producer: 'Producer / Admin',
      producerDesc: 'Access master control room',
      enter: 'Enter',
      welcome: 'Welcome to',
      // Email auth
      email: 'Email',
      password: 'Password',
      name: 'Name',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      orContinueWith: 'or continue with',
      useEmail: 'Use Email',
      useGoogle: 'Use Google',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      createAccount: 'Create account',
      loginHere: 'Login here',
      emailRequired: 'Email is required',
      passwordRequired: 'Password is required',
      passwordMinLength: 'Password must be at least 6 characters',
      signUpSuccess: 'Account created! Check your email to confirm.',
      username: 'Username',
      usernameTaken: 'This username is already taken',
      usernameInvalid: 'Username can only contain letters, numbers, underscores and hyphens',
      usernameTooShort: 'Username must be at least 3 characters',
      forgotPassword: 'Forgot password?',
      resetPassword: 'Reset Password',
      sendResetLink: 'Send Reset Link',
      backToLogin: 'Back to Login',
      resetEmailSent: 'Reset email sent! Check your inbox.',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      passwordsDoNotMatch: 'Passwords do not match',
      passwordResetSuccess: 'Password reset successfully! Please login.',
      enterEmailForReset: 'Enter your email to receive reset link'
    },
    nav: {
      stage: 'Main Stage',
      rooms: 'Breakout Rooms',
      parties: 'My Parties',
      agenda: 'Agenda',
      networking: 'Networking',
      admin: 'Control Room',
      analytics: 'Analytics',
      settings: 'Settings',
      signout: 'Sign Out',
      producer: 'Producer Tools'
    },
    stage: {
      live: 'LIVE',
      viewers: 'Viewers',
      about: 'About This Session',
      track: 'Track',
      level: 'Level',
      addToCalendar: 'Add to Calendar',
      share: 'Share'
    },
    engagement: {
      chat: 'Chat',
      qa: 'Q&A',
      polls: 'Polls',
      survey: 'Survey',
      liveChat: 'Live Chat',
      aiSummary: 'AI Summary',
      analyzing: 'Analyzing...',
      typeMessage: 'Type a message...',
      topQuestions: 'Top Questions',
      askQuestion: 'Ask Question',
      answered: 'Answered',
      currentPoll: 'Current Poll',
      votes: 'votes',
      submitFeedback: 'Submit Feedback',
      thankYou: 'Thank You!',
      feedbackRecorded: 'Your feedback has been recorded.',
      noSurvey: 'No active surveys at this moment.',
      connection: 'Excellent Connection'
    },
    admin: {
      title: 'MCR - Master Control Room',
      onAir: 'ON AIR',
      streamHealth: 'Signal & Source',
      activeViewers: 'Real-Time Audience',
      registered: 'Registered',
      aiDirector: 'AI Director',
      createPoll: 'Launch Poll',
      createSurvey: 'Launch Survey',
      drafting: 'Drafting...',
      dangerZone: 'Critical Zone',
      restart: 'Restart Signal',
      endEvent: 'Cut Transmission',
      bitrate: 'Bitrate',
      fps: 'FPS',
      dropped: 'Dropped Frames',
      back: 'Back to Login'
    },
    reports: {
      title: 'User Reports',
      export: 'Export CSV',
      searchPlaceholder: 'Search by name, email or ID...',
      columns: {
        user: 'User',
        role: 'Role',
        session: 'Session',
        engagement: 'Engagement',
        location: 'Location',
        actions: 'Actions'
      },
      details: {
        techInfo: 'Technical Info',
        activityLog: 'Activity Log',
        questions: 'Questions Asked',
        browser: 'Browser',
        device: 'Device',
        ip: 'IP Address',
        connection: 'Connection',
        login: 'Login',
        logout: 'Logout',
        duration: 'Duration'
      }
    },
    rooms: {
      title: 'Live Sessions & Breakouts',
      subtitle: 'Choose a track to join live interactive sessions.',
      join: 'Join Session'
    },
    projects: {
      title: 'Manage Projects',
      createNew: 'New Project',
      selectProject: 'Select Project',
      deleteProject: 'Delete Project',
      projectName: 'Project Name',
      projectDescription: 'Description',
      status: 'Status',
      draft: 'Draft',
      live: 'Live',
      ended: 'Ended',
      onDemand: 'On Demand',
      onDemandDesc: 'Available for viewing after event ends',
      enableOnDemand: 'Enable On-Demand',
      disableOnDemand: 'Disable On-Demand',
      currentProject: 'Current Project',
      noProjects: 'No projects created',
      confirmDelete: 'Are you sure you want to delete this project?',
      create: 'Create',
      cancel: 'Cancel',
      save: 'Save',
      viewers: 'Views',
      createdAt: 'Created at',
      rtmpStreamKey: 'RTMP Stream Key',
      rtmpUrl: 'RTMP URL',
      streamingDetails: 'Streaming Details',
      copyKey: 'Copy Key',
      keyCopied: 'Key copied!'
    }
  }
};

// All mock data has been removed - the app now uses real data from Supabase